version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: youtube_videos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YOUR_PASSWORD_HERE